---
  root: true

  env:
    commonjs: true
    es6: true

  extends: eslint:recommended

  ecmaFeatures:
    module: true
    modules: true

  parser: babel-eslint

  parserOptions:
    sourceType: module

  rules:
    no-unused-vars: [error, { vars: local, args: after-used, argsIgnorePattern: ^_ }]
