---
  root: true

  env:
    commonjs: true
    es6: true

  extends: eslint:recommended

  parser: babel-eslint

  parserOptions:
    ecmaFeatures:
      module: true
    ecmaVersion: 6
    sourceType: module

  rules:
    no-unused-vars: [error, { vars: local, args: after-used, argsIgnorePattern: ^_ }]
