---
  env:
    browser: true

  plugins:
  - flowtype
  - react

  parserOptions:
    ecmaFeatures:
      jsx: true

  rules:
    flowtype/boolean-style: error
    flowtype/define-flow-type: error
    flowtype/delimiter-dangle: [error, always]
    flowtype/generic-spacing: [error, never]
    flowtype/no-dupe-keys: error
    flowtype/no-primitive-constructor-types: error
    flowtype/object-type-delimiter: [error, semicolon]
    flowtype/space-after-type-colon: error
    flowtype/space-before-generic-bracket: [error, never]
    flowtype/space-before-type-colon: [error, never]
    flowtype/union-intersection-spacing: error
    flowtype/use-flow-type: error
    react/jsx-uses-react: error
    react/jsx-uses-vars: error
