---
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    config: client/.eslintrc.yml
ratings:
  paths:
  - client/src/**.js
  - client/src/**.jsx
  - lib/**.rb
exclude_paths:
- client/flow-typed/**/*
- lib/generators/**/*.js
- sample/**/*
