AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - client/**/*
  - node_modules/**/*
  - sample/**/*
  - vendor/**/*

Metrics/BlockLength:
  Exclude:
  - lib/admin_core/rspec/**/*
  - spec/**/*

Metrics/LineLength:
  Max: 125

Style/ClassAndModuleChildren:
  Exclude:
  - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
